name: Assign Current Issue

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/assign-current-issue.yml'

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to copilot
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = 9; // This is the current issue number
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            try {
              // Check if the issue exists and is unassigned
              const issue = await github.rest.issues.get({
                owner,
                repo,
                issue_number: issueNumber,
              });
              
              if (!issue.data.assignee) {
                console.log(`Assigning issue #${issueNumber} to 'copilot'...`);
                
                // Assign to 'copilot'
                await github.rest.issues.addAssignees({
                  owner,
                  repo,
                  issue_number: issueNumber,
                  assignees: ['copilot'],
                });
                
                console.log(`Issue #${issueNumber} has been assigned to 'copilot'`);
              } else {
                console.log(`Issue #${issueNumber} already has an assignee: ${issue.data.assignee.login}`);
              }
            } catch (error) {
              console.error(`Error checking or assigning issue: ${error.message}`);
            }