name: Link PRs and Issues to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  link-to-project:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'lotape6' || github.actor == 'copilot'
    steps:
      - name: Link to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/lotape6/projects/1
          github-token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Assign Copilot (if possible)
        if: github.actor == 'lotape6'
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-assignee copilot --add-label "status: ready" 
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}