name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and run Docker test
        run: |
          docker build -f test/Dockerfile.test -t mytools-test .
          docker run --rm mytools-test