name: Auto Issue Assignment

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 30 seconds
        run: sleep 30
        
      - name: Check and assign issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Get current issue data
            const issue = await github.rest.issues.get({
              owner,
              repo,
              issue_number: issueNumber,
            });
            
            // Check if the issue is still unassigned
            if (!issue.data.assignee) {
              console.log(`Issue #${issueNumber} is still unassigned after 30 seconds. Assigning to 'copilot'...`);
              
              // Assign to 'copilot'
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: ['copilot'],
              });
              
              console.log(`Issue #${issueNumber} has been assigned to 'copilot'`);
            } else {
              console.log(`Issue #${issueNumber} already has an assignee: ${issue.data.assignee.login}`);
            }